version: '3.9'
services:
  db:
    image: postgres
    container_name: soldartemetal-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234soldarte
      POSTGRES_DB: soldarte_db
    ports:
        - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  